### PR TITLE
Feature/pelahi forhighrest

### PR DESCRIPTION
**Pull request by pelahi**
This a suggested update to the high rest implementation. 
There are several different commits, the first few just changing/adding some code. The last few actually remove some added changes (such as removing the variety of KDTree constructors). 
My suggestion is to carefully look at the commit history and the test associated with each commit first. The critical change for your branch of VR is that there are no longer several KDTree constructors. Instead, the adaptive constructor is automatically invoked if the appropriate variable is passed with a non-zero value (this being the size which indicates a leaf node is identified). 

So again, commits that just update KDTree to have normal constructor be able to generate adaptive 
- https://github.com/JinsuRhee/NBodylib/commit/f0365ca4a806c690ae1139aed801912d877b342c
- https://github.com/JinsuRhee/NBodylib/commit/5186008e3de2592bd8c6e2cb84357228c62cbd77
- https://github.com/JinsuRhee/NBodylib/commit/55f21be24172f605e9c624fbc817e8ae7138670d

Add split node closing in a FOF search and change FOF criterion searches back to original
- https://github.com/JinsuRhee/NBodylib/commit/f6914890030c5e0213acdc917972dc0173f03eaa

Remove added constructors
- https://github.com/JinsuRhee/NBodylib/commit/18c8e922a307c941fb0180718b6baf066f67b7b8

### CODE REVIEW

**Comment by pelahi** [comment]
> I think this is the wrong implementation.
> Let's think about an one-dimensional case with maxr2 = 10, farthest = 1, and fdist2 = 10.5.
> Then, if then the distance of the farthest particle to the target particle is either 9 or 11, where the latter case is not inside the search radius.
> 
> This should be
> 
> inodeflagged = ( | sqrt(fdist2) - sqrt(farthest) | >= sqrt(maxr2) && farthest < fdist2 )
> 
> This formula ensures that the search radius entirely encompasses all particles in this node. What do you think?

Yes, sorry, forgot the sqrt().

**Comment by pelahi** [comment]
> If sqrt(maxr2) > sqrt(farthest) + sqrt(fdist2), this node is entirely outside the search radius so that we can skip this node. I think this can reduce some needless calculations. What do you think?

That seems reasonable. Did you want to add this and also correct the inodeflagged error?

**Comment by pelahi** [comment]
I've also added the ability to not split at the median but in a region around the median based on the largest distance between adjacent particles. Have a look at the last commit. Could you updated your VR to make use of this updated NBobylib API and test it?

**Comment by JinsuRhee** [comment]
OK. I look through the commit history. I'll test it now.

**Pull request merged**
